name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  ubuntu:
    name: ubuntu perl ${{ matrix.perl-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.14-buster'
          - '5.16-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.22-buster'
          - '5.24-buster'
          - '5.26-buster'
          - '5.28-buster'
          - '5.30-buster'
          - '5.32-buster'
          - '5.34-buster'
          - '5.36-buster'
          - '5.38-buster'
          - 'latest'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -fsSL --compressed https://raw.githubusercontent.com/skaji/cpm/main/cpm | perl - install -g --with-configure --show-build-log-on-failure
      - name: Run Build.PL
        run: perl Build.PL
      - name: Run Build
        run: ./Build build
      - name: Run Tests
        run: ./Build test
